display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- All -'
      fields:
        created:
          label: Created
        view_webform_submission:
          label: Operations
      arguments:
        in_draft:
          exception:
            title: All
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
        created:
          label: Created
        operations:
          label: Operations
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
        created:
          label: Created
        view_webform_submission:
          label: Operations
        edit_webform_submission:
          label: Operations
  embed_review:
    display_options:
      fields:
        created:
          label: Created
        view_webform_submission:
          label: Operations
