label: 'المستخدمون الجدد'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      title: 'المستخدمون الجدد'
  block_1:
    display_title: 'المستخدمون الجدد'
    display_options:
      block_description: 'المستخدمون الجدد'
      block_category: المستخدم
