settings:
  default_reset_button_label: Reset
  default_preview_next_button_label: معاينة
  default_preview_label: معاينة
  dialog_options:
    wide:
      title: واسع
element:
  default_more_title: المزيد
