heritage_custom_configs.admin_settings:
  title: 'Custom Configurations'
  parent: heritage_custom_configs.admin_config
  description: 'Configure Custom Settings.'
  route_name: heritage_custom_configs.admin_settings