heritage_custom_configs.admin_config:
  path: '/admin/config/heritage_configs_settings'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Heritage Trail custom config Settings'
    _description: 'Manage Heritage Trail custom config Settings.'
  requirements:
    _permission: 'administer site configuration'   
heritage_custom_configs.admin_settings:
  path: '/admin/config/heritage_custom_configs_settings'
  defaults:
    _form: '\Drupal\heritage_custom_configs\Form\CustomConfigsSettingsForm'
    _title: 'Custom Configuration Settings'
  requirements:
    _permission: 'administer custom configuration settings'    
