marsana_custom_configs.admin_settings:
  title: 'Custom Configurations'
  parent: marsana_custom_configs.admin_config
  description: 'Configure Custom Settings.'
  route_name: marsana_custom_configs.admin_settings