hudayriyat_custom_configs.admin_config:
  path: '/admin/config/hudayriyat_configs_settings'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Hudayriyat custom config Settings'
    _description: 'Manage Hudayriyat custom config Settings.'
  requirements:
    _permission: 'administer site configuration'   
hudayriyat_custom_configs.admin_settings:
  path: '/admin/config/hudayriyat_custom_configs_settings'
  defaults:
    _form: '\Drupal\hudayriyat_custom_configs\Form\CustomConfigsSettingsForm'
    _title: 'Custom Configuration Settings'
  requirements:
    _permission: 'administer custom configuration settings'   
